        ##########################################################
        ## Turn On Front Door when Door Bell Rings
        ##########################################################

- alias: Doorbell - Turn On Front Door when Rung

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness_pct: 100
        kelvin: 2700

        ##########################################################
        ## Reset Front Door Brightness After Doorbell Rings
        ##########################################################

- alias: Doorbell - Reset Front Door After Ring

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: scene.turn_on
      data_template:
        entity_id: scene.front_{{ states.input_select.outdoor_theme.state | lower | replace(' ', '_') | replace('\'', '') }}

        ##########################################################
        ## Turn On Front Door when Motion Detected
        ##########################################################

- alias: Doorbell - Turn On Front Door when Motion Detected

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness_pct: 100
        kelvin: 2700

        ##########################################################
        ## Reset Front Door After Motion Detected - Before Off
        ##########################################################

- alias: Doorbell - Reset Front Door After Motion Detected before 11:30

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: time
      before: '23:30:00'       

  action:
    - service: light.turn_on
      entity_id: light.front_door
      data:
        brightness_pct: 30
        kelvin: 2700
        ##########################################################
        ## Reset Front Door After Motion Detected - After Off
        ##########################################################

- alias: Doorbell - Reset Front Door After Motion Detected after 11:30

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_motion
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0
      
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'
    - condition: time
      before: '06:30:00'
    - condition: time  
      after: '23:30:00' 
  action:
    - service: light.turn_off
      entity_id: light.front_door
              
        ##########################################################
        ## Door Bell Rings - Audio Notification
        ##########################################################

- alias: Doorbell - Play Sound When Someone Rings Doorbell

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_ding
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_doorbell
      state: 'off'

  action:
#    - service: sonos.join
#      data:
#        master: media_player.office  
#      entity_id:
#        - media_player.office2
#    - delay: '00:00:02'
    - service: media_player.volume_set
      entity_id:
        - media_player.office
      data:
        volume_level: '0.6'
    - delay: '00:00:01'
    - service: tts.amazon_polly_say
      entity_id: media_player.office
      data:
        message: 'Someone is at the Front Door.'
