#################################################################
## Inside Lighting Automation
#################################################################

        ##########################################################
        ## Household Home Turn on Lights
        ##########################################################

- alias: Household Home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

  action:
    service: light.turn_on
    entity_id: light.family_room
    data:
     brightness: 255

        ##########################################################
        ## Pantry Light On When Door Open
        ##########################################################

- alias: Pantry Light On

  trigger:
    - platform: state
      entity_id: binary_sensor.pantry_door
      from: 'off'
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.pantry_lights
    data:
     brightness: 255

        ##########################################################
        ## Pantry Light Off When Door Open
        ##########################################################

- alias: Pantry Light Off

  trigger:
    - platform: state
      entity_id: binary_sensor.pantry_door
      from: 'on'
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.pantry_lights

        ##########################################################
        ## Hall Closet Lights On When Door Open
        ##########################################################

- alias: Hall Closet Light On

  trigger:
    - platform: state
      entity_id: binary_sensor.hall_closet_door
      from: 'off'
      to: 'on'

  action:
    service: light.turn_on
    entity_id: light.hall_closet_lights
    data:
     brightness: 255

        ##########################################################
        ## Hall Closet Lights Off When Door Open
        ##########################################################

- alias: Hall Closet Lights Off

  trigger:
    - platform: state
      entity_id: binary_sensor.hall_closet_door
      from: 'on'
      to: 'off'

  action:
    service: light.turn_off
    entity_id: light.hall_closet_lights

        ##########################################################
        ## Hall Closet Lights Off When On for 10 Minutes
        ##########################################################

- alias: Hall Closet Lights Off - Left Open

  trigger:
    - platform: state
      entity_id: light.hall_closet_lights
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  action:
    - service: notify.mobile_app_USER1_iphone
      data:
        message: Hall Closet Lights Left On!
        data:
          apns_headers:
           'apns-collapse-id': 'hallcloset-lights'
          push:
            badge: 0
            category: "hallclosetlights"

        ##########################################################
        ## Basement Light Off When No Motion 60 Minutes
        ##########################################################

- alias: Basement Lights Off

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_motion_sensor
      from: 'on'
      to: 'off'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  action:
    service: light.turn_off
    entity_id: light.basement

        ##########################################################
        ## Turn off Kids Bedroom Night Lights at 11:00pm
        ##########################################################

- alias: Kids Lights Off

  trigger:
    - platform: time
      at: '23:00'

  action:
    - service: light.turn_off
      entity_id: light.USER4_bedroom
    - service: light.turn_off
      entity_id: light.USER3_bedroom
