##################################################################
## Basement Default Mode
##################################################################

        ##########################################################
        ## Default Mode
        ##########################################################

- alias: Basement Theme - Default On

  trigger:
    - platform: state
      entity_id: input_select.basement_theme
      to:  'Default'

  action:
    - service: light.turn_on
      entity_id: light.basement_sitting_area
      data:
        transition: 5
        brightness_pct: 100
        effect: "Warm White"
    - service: light.turn_on
      entity_id: light.basement_entry
      data:
        transition: 5
        brightness_pct: 100
        effect: "Warm White"